Repository City-of-Helsinki/kukkuu-ui, pull requests merged in 2019-12, with the labels that each got.

#50 KK-123 | Add key to child list
  src/domain/api/generatedTypes/profileQuery.ts
  src/domain/profile/Profile.tsx
  src/domain/profile/queries/ProfileQuery.ts
  src/domain/profile/state/ProfileReducers.tsx
Labels: enhancement

#51 Add better state managing with home form action handler
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/types/HomeFormTypes.ts
  src/domain/registration/constants/RegistrationActionConstants.tsx
  src/domain/registration/notEligible/NotEligibleUtils.ts
  src/domain/registration/state/RegistrationActions.tsx
  src/domain/registration/state/RegistrationReducers.tsx
Labels: enhancement

#52 Customizable container background
  src/assets/styles/mixins.scss
  src/assets/styles/variables.scss
  src/common/components/input/input.module.scss
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/footer/footer.module.scss
  src/domain/app/layout/Container.tsx
  src/domain/app/layout/Layout.tsx
  src/domain/app/layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/domain/app/layout/layout.module.scss
  src/domain/app/notFound/NotFound.tsx
  src/domain/home/Home.tsx
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/partial/BirthdateFormField.tsx
  src/domain/home/form/partial/__tests__/__snapshots__/BirthdateFormField.test.tsx.snap
  src/domain/profile/Profile.tsx
  src/domain/profile/profile.module.scss
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/form/registrationForm.module.scss
  src/domain/registration/notEligible/NotEligible.tsx
  src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap
  src/domain/registration/welcome/Welcome.tsx
  src/domain/registration/welcome/__tests__/__snapshots__/Welcome.test.tsx.snap
Labels: enhancement

#53 KK-121 | Complete styling for registration form, add some designer proposal styles.
  src/assets/icons/svg/adultFaceHappy.svg
  src/assets/icons/svg/childFaceHappy.svg
  src/assets/icons/svg/happyChild.svg
  src/assets/styles/variables.scss
  src/common/components/input/input.module.scss
  src/common/components/modal/Modal.tsx
  src/domain/app/footer/footer.module.scss
  src/domain/app/header/header.module.scss
  src/domain/app/layout/container.module.scss
  src/domain/home/form/homePreliminaryForm.module.scss
  src/domain/home/home.module.scss
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/form/partial/ChildFormField.tsx
  src/domain/registration/form/partial/childFormField.module.scss
  src/domain/registration/form/registrationForm.module.scss
Labels: enhancement

#55 KK-124 | Validation for postal code
  src/common/components/form/__tests__/validationUtils.tests.tsx
  src/common/components/form/validationUtils.tsx
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/registration/form/partial/ChildFormField.tsx
Labels: enhancement

#54 KK-125 | Add a proper GuardianInput for better typing
  src/domain/api/generatedTypes/globalTypes.ts
  src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts
Labels: enhancement

#57 Add postalCode and relationship to submit child mutation
  src/domain/api/generatedTypes/globalTypes.ts
  src/domain/api/generatedTypes/profileQuery.ts
  src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
  src/domain/profile/queries/ProfileQuery.ts
  src/domain/profile/state/ProfileReducers.tsx
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/partial/ChildFormField.tsx
Labels: enhancement

#58 Fix checkbox to not taking full width, as well as accesibility control
  src/common/components/input/input.module.scss
Labels: bug

#59 Update mutation to support change in schema
  src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
  src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts
Labels: enhancement

#60 KK-135 | Add a custom translated title for each page
  package.json
  public/index.html
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/navbar/__tests__/__snapshots__/Navbar.test.tsx.snap
  src/domain/app/layout/Layout.tsx
  src/domain/app/layout/PageWrapper.tsx
  src/domain/app/layout/__tests__/PageWrapper.test.tsx
  src/domain/app/layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/domain/app/layout/__tests__/__snapshots__/PageWrapper.test.tsx.snap
  src/domain/home/Home.tsx
  src/domain/home/__tests__/Home.test.tsx
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/profile/Profile.tsx
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/notEligible/NotEligible.tsx
  src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap
  src/domain/registration/welcome/Welcome.tsx
  src/domain/registration/welcome/__tests__/__snapshots__/Welcome.test.tsx.snap
  yarn.lock
Labels: enhancement

#61 KK-98 | Profile children listing
  .env.development
  src/assets/icons/svg/birthdayCake.svg
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/profile/Profile.tsx
  src/domain/profile/ProfileUtils.ts
  src/domain/profile/children/ProfileChild.tsx
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/profile/children/profileChild.module.scss
  src/domain/profile/children/profileChildrenList.module.scss
  src/domain/profile/events/ProfileNoEvent.tsx
  src/domain/profile/profile.module.scss
  src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap
Labels: enhancement

#62 Registration form preferred language should default to UI language
  src/domain/registration/form/RegistrationForm.tsx
Labels: enhancement

#64 KK-99 | Profile child detail information
  src/assets/icons/svg/arrowLeft.svg
  src/assets/icons/svg/envelopeWithStars.svg
  src/assets/icons/svg/mobile.svg
  src/assets/styles/variables.scss
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/api/generatedTypes/profileQuery.ts
  src/domain/app/App.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/layout/PageWrapper.tsx
  src/domain/app/layout/__tests__/__snapshots__/PageWrapper.test.tsx.snap
  src/domain/app/layout/pageWrapper.module.scss
  src/domain/auth/OidcCallback.tsx
  src/domain/profile/Profile.tsx
  src/domain/profile/ProfileUtils.ts
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/profile/children/child/ProfileChild.tsx
  src/domain/profile/children/child/ProfileChildDetail.tsx
  src/domain/profile/children/child/profileChild.module.scss
  src/domain/profile/children/child/profileChildDetail.module.scss
  src/domain/profile/children/profileChildrenList.module.scss
  src/domain/profile/events/ProfileNoEvent.tsx
  src/domain/profile/events/profileNoEvent.module.scss
  src/domain/profile/profile.module.scss
  src/domain/profile/queries/ProfileQuery.ts
  src/domain/profile/state/ProfileReducers.tsx
  src/domain/profile/state/ProfileSelectors.ts
  src/domain/profile/type/ProfileTypes.ts
Labels: enhancement

#65 Language detection should actually be used
  src/common/test/testi18nInit.ts
  src/common/translation/i18n/i18nInit.ts
  src/setupTests.ts
Labels: bug

#66 KK-192 | Add child profile page
  src/assets/icons/svg/envelopeWithStars.svg
  src/assets/icons/svg/tada.svg
  src/common/components/modal/modal.module.scss
  src/domain/api/generatedTypes/addNewChild.ts
  src/domain/api/generatedTypes/globalTypes.ts
  src/domain/child/ChildUtils.ts
  src/domain/child/mutation/ChildMutation.ts
  src/domain/child/types/ChildTypes.ts
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/profile/children/profileChildrenList.module.scss
  src/domain/registration/form/RegistrationForm.tsx
Labels: enhancement

#67 KK-123 | Add not eligible warning for child modal
  src/common/components/modal/Modal.tsx
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/child/modal/childFormModal.module.scss
  src/domain/registration/form/partial/ChildFormField.tsx
  src/domain/registration/modal/AddNewChildFormModal.tsx
Labels: enhancement

#68 KK-139 | add language bar for big home screen
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/navbar/Navbar.tsx
  src/domain/app/header/navbar/__tests__/__snapshots__/Navbar.test.tsx.snap
  src/domain/app/header/navbar/languageBar/LanguageBar.tsx
  src/domain/app/header/navbar/languageBar/languageBar.module.scss
  src/domain/registration/form/RegistrationForm.tsx
Labels: enhancement

#63 KK-146 | Add error handling using react-toastify
  package.json
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/api/client.ts
  src/domain/app/App.tsx
  src/domain/auth/OidcCallback.tsx
  src/domain/auth/authenticate.ts
  src/domain/auth/getAuthenticatedUser.ts
  src/domain/profile/Profile.tsx
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/registration/form/RegistrationForm.tsx
  yarn.lock
Labels: enhancement

#69 KK-152 | Fix language validation error on registration form
  src/domain/registration/form/RegistrationForm.tsx
Labels: bug

#70 KK-153 | Use correct relationship format for submit add child mutations
  src/common/components/form/__tests__/validationUtils.tests.tsx
  src/common/components/form/validationUtils.tsx
  src/domain/child/ChildUtils.ts
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/child/modal/__tests__/__snapshots__/ChildFormModal.test.tsx.snap
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/state/RegistrationReducers.tsx
  src/domain/registration/types/RegistrationTypes.ts
Labels: bug

#71 KK-135 | KK-137 | Layout for hero and instructions
  src/assets/icons/svg/homeKid.svg
  src/assets/icons/svg/homeTheater.svg
  src/assets/icons/svg/homeTicket.svg
  src/assets/icons/svg/kids.png
  src/assets/styles/layout.scss
  src/assets/styles/variables.scss
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/header/navbar/languageBar/LanguageBar.tsx
  src/domain/app/header/navbar/languageBar/languageBar.module.scss
  src/domain/app/layout/container.module.scss
  src/domain/home/Home.tsx
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
  src/domain/home/form/homePreliminaryForm.module.scss
  src/domain/home/hero/HomeHero.tsx
  src/domain/home/hero/hero.module.scss
  src/domain/home/home.module.scss
  src/domain/home/instructions/HomeInstructions.tsx
  src/domain/home/instructions/homeInstructions.module.scss
Labels: enhancement

#72 Users should not see registration form any more after submitting it
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/state/RegistrationSelectors.ts
  src/domain/registration/welcome/Welcome.tsx
  src/domain/registration/welcome/__tests__/Welcome.test.tsx
  src/domain/registration/welcome/__tests__/__snapshots__/Welcome.test.tsx.snap
Labels: enhancement

#73 KK-136 | KK-138 Add contact, partners
  src/assets/icons/partners/cirko.png
  src/assets/icons/partners/heka.png
  src/assets/icons/partners/hki.png
  src/assets/icons/partners/ilmi.png
  src/assets/icons/partners/jane.png
  src/assets/icons/partners/tansi.png
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/home/Home.tsx
  src/domain/home/contact/HomeContact.tsx
  src/domain/home/contact/homeContact.module.scss
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
  src/domain/home/form/homePreliminaryForm.module.scss
  src/domain/home/hero/HomeHero.tsx
  src/domain/home/home.module.scss
  src/domain/home/partners/HomePartners.tsx
  src/domain/home/partners/homePartners.module.scss
Labels: enhancement

#75 Update translations from translator
  scripts/update-translations.ts
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
Labels: enhancement

#76 Add more translations from translator
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
Labels: enhancement

#78 Add autoclose for dropdown, fix overflow
  src/common/components/dropdown/Dropdown.tsx
  src/common/components/dropdown/dropdown.module.scss
  src/domain/app/layout/container.module.scss
Labels: bug

#77 Tweaks to design
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/home/contact/HomeContact.tsx
  src/domain/home/contact/homeContact.module.scss
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
  src/domain/home/form/homePreliminaryForm.module.scss
  src/domain/home/form/partial/__tests__/__snapshots__/BirthdateFormField.test.tsx.snap
  src/domain/home/hero/hero.module.scss
  src/domain/home/instructions/HomeInstructions.tsx
  src/domain/home/instructions/homeInstructions.module.scss
  src/domain/home/partners/HomePartners.tsx
  src/domain/home/partners/homePartners.module.scss
  src/domain/profile/Profile.tsx
Labels: enhancement

#74 Clear user data from browser when logging out
  src/domain/app/header/userDropdown/UserDropdown.tsx
  src/domain/auth/authenticate.ts
  src/domain/auth/constants/BackendAuthenticationActionConstants.ts
  src/domain/auth/state/BackendAuthenticationActions.ts
  src/domain/auth/state/BackendAuthenticationReducer.ts
Labels: enhancement

#81 Fix submitChildrenAndGuardian - take api change into account
  src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
  src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts
Labels: enhancement

#80 If logging in without a profile, be redirected to the front page
  src/domain/profile/Profile.tsx
  src/domain/profile/profile.module.scss
Labels: bug

#82 Create a better menu for mobile & bonus fixes
  src/assets/icons/svg/hamburgerMenu.svg
  src/common/components/dropdown/Dropdown.tsx
  src/common/components/dropdown/dropdown.module.scss
  src/common/translation/TranslationConstants.ts
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/navbar/Navbar.tsx
  src/domain/app/header/navbar/__tests__/__snapshots__/Navbar.test.tsx.snap
  src/domain/app/header/navbar/languageBar/LanguageBar.tsx
  src/domain/app/header/navbar/languageBar/languageBar.module.scss
  src/domain/app/header/navbar/navbar.module.scss
  src/domain/app/header/navbar/smallScreenNav/SmallScreenNav.tsx
  src/domain/app/header/navbar/smallScreenNav/smallScreenNav.module.scss
  src/domain/app/header/userDropdown/UserDropdown.tsx
  src/domain/app/header/userMenu/UserMenu.tsx
  src/domain/app/header/userMenu/userMenu.module.scss
  src/domain/app/layout/container.module.scss
  src/domain/app/state/AppStore.ts
  src/domain/auth/authenticate.ts
  src/domain/home/form/homePreliminaryForm.module.scss
  src/domain/home/partners/homePartners.module.scss
Labels: bug, enhancement

#83 Overlay should be vertically scrollable on mobile
  src/common/components/modal/modal.module.scss
Labels: bug

#84 If child is not eligible, link to myhelsinki. In modal: Close window
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/registration/notEligible/NotEligible.tsx
  src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap
Labels: enhancement

#85 Move ToastContainer so it doesn't cause unwanted white space
  src/domain/app/App.tsx
  src/domain/app/BrowserApp.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
Labels: bug

#87 Better margins and less horizontal overflow on small screens
  src/domain/profile/children/child/profileChildDetail.module.scss
  src/domain/profile/children/profileChildrenList.module.scss
  src/domain/profile/events/profileNoEvent.module.scss
  src/domain/registration/welcome/welcome.module.scss
Labels: enhancement

#88 KK-171 | Cursor should jump between fields in modal when hitting tab key
  src/common/components/modal/modal.module.scss
Labels: bug

#89 KK-171 | Accessibility improvements
  src/common/components/dropdown/dropdown.module.scss
  src/common/components/input/input.module.scss
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/domain/app/header/navbar/languageDropdown/languageDropdown.module.scss
  src/domain/app/header/navbar/smallScreenNav/SmallScreenNav.tsx
  src/domain/app/header/navbar/smallScreenNav/smallScreenNav.module.scss
  src/domain/app/header/userMenu/UserMenu.tsx
  src/domain/app/header/userMenu/userMenu.module.scss
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/partial/BirthdateFormField.tsx
  src/domain/home/form/partial/__tests__/__snapshots__/BirthdateFormField.test.tsx.snap
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/profile/children/child/ProfileChild.tsx
  src/domain/profile/children/child/ProfileChildDetail.tsx
  src/domain/profile/children/child/profileChild.module.scss
  src/domain/profile/children/child/profileChildDetail.module.scss
  src/domain/profile/children/profileChildrenList.module.scss
Labels: enhancement

#90 KK-160 | Add all front page partner logos
  src/assets/icons/partners/amosrex.png
  src/assets/icons/partners/cirko.png
  src/assets/icons/partners/designmuseum.png
  src/assets/icons/partners/hamhelsinki.png
  src/assets/icons/partners/heka.png
  src/assets/icons/partners/hel.png
  src/assets/icons/partners/helsinginkaupunginmuseo.png
  src/assets/icons/partners/helsinginkaupunginorkesteri.png
  src/assets/icons/partners/hkt.png
  src/assets/icons/partners/hotellijaravintolamuseo.png
  src/assets/icons/partners/hurjaruuth.png
  src/assets/icons/partners/ilmi.png
  src/assets/icons/partners/jaes.png
  src/assets/icons/partners/kansallismuseo.png
  src/assets/icons/partners/kansallisteatteri.png
  src/assets/icons/partners/kavi.png
  src/assets/icons/partners/kulttuuriperintokasvatus.png
  src/assets/icons/partners/mfa.png
  src/assets/icons/partners/nukketeatterisampo.png
  src/assets/icons/partners/oodihelsinki.png
  src/assets/icons/partners/oopperabaletti.png
  src/assets/icons/partners/qteatteri.png
  src/assets/icons/partners/svenskateatern.png
  src/assets/icons/partners/tansi.png
  src/assets/icons/partners/tanssintalo.png
  src/assets/icons/partners/teatteriilmio.png
  src/assets/icons/partners/teatterimuseo.png
  src/assets/icons/partners/valokuvataiteenmuseo.png
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/home/partners/HomePartners.tsx
  src/domain/home/partners/PartnerLogoList.tsx
  src/domain/home/partners/__tests__/Partners.test.tsx
  src/domain/home/partners/__tests__/__snapshots__/Partners.test.tsx.snap
  src/domain/home/partners/constants/PartnersConstants.tsx
  src/domain/home/partners/homePartners.module.scss
  src/domain/home/partners/partnerLogoList.module.scss
  src/domain/home/partners/types/partner.ts
Labels: enhancement
