Repository City-of-Helsinki/kukkuu-ui, pull requests merged in 2019-11, with the labels that each got.

#22 KK-28 | Registration form scaffolding.
  package.json
  src/common/components/form/__tests__/validationUtils.tests.tsx
  src/common/components/form/fields/input/InputField.tsx
  src/common/components/form/fields/input/inputField.module.scss
  src/common/components/form/fields/select/SelectField.tsx
  src/common/components/form/fields/select/__tests__/SelectField.test.tsx
  src/common/components/form/fields/select/__tests__/__snapshots__/SelectField.test.tsx.snap
  src/common/components/form/fields/select/selectField.module.scss
  src/common/components/form/validationUtils.tsx
  src/common/components/input/Input.tsx
  src/common/components/input/__tests__/__snapshots__/Input.test.tsx.snap
  src/common/components/input/input.module.scss
  src/common/components/spinner/LoadingSpinner.tsx
  src/common/components/spinner/__tests__/__snapshots__/LoadingSpinner.test.tsx.snap
  src/common/test/TestForm.tsx
  src/common/time/TimeConstants.ts
  src/common/translation/TranslationConstants.ts
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/common/translation/utils.tsx
  src/domain/app/App.tsx
  src/domain/app/BrowserApp.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/state/AppReducers.ts
  src/domain/app/state/AppStore.ts
  src/domain/app/types/stateTypes.ts
  src/domain/auth/route/PrivateRoute.tsx
  src/domain/auth/route/__tests__/PrivateRoute.test.tsx
  src/domain/auth/state/authSelectors.ts
  src/domain/home/Home.tsx
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
  src/domain/home/form/partial/BirthdayFormField.tsx
  src/domain/home/form/partial/__tests__/BirthdayFormField.test.tsx
  src/domain/home/form/partial/__tests__/__snapshots__/BirthdayFormField.test.tsx.snap
  src/domain/home/form/partial/birthdayFormField.module.scss
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/RegistrationForm.test.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/form/registrationForm.module.scss
  src/domain/registration/state/RegistrationReducers.tsx
  src/domain/registration/state/RegistrationSelectors.ts
  src/domain/registration/types/RegistrationTypes.ts
  src/domain/registration/types/RegistrationTypes.tsx
  src/setupTests.ts
  yarn.lock
Labels: enhancement

#21 KK-29 | Add graphql to the project
  .env
  .env.development
  README.md
  apollo.config.js
  package.json
  src/domain/api/__tests__/client.test.ts
  src/domain/api/client.ts
  src/domain/api/generatedTypes/DummyQuery.ts
  src/domain/api/generatedTypes/globalTypes.ts
  src/domain/api/generatedTypes/submitChild.ts
  src/domain/app/BrowserApp.tsx
  src/domain/registration/mutations/submitChild.ts
  src/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#24 Use port 8081 for kukkuu backend according to upcoming docker PR
  .env.development
Labels: enhancement

#26 Update readme to get tunnistamo api keys working
  .env.development
  README.md
Labels: enhancement

#25 KK-77 | Add silent_renew token when expired, auto-fetch apiToken when accesstoken exist
  .env.development
  .eslintrc.json
  package.json
  src/domain/api/client.ts
  src/domain/api/constants/ApiConstants.ts
  src/domain/app/App.tsx
  src/domain/app/BrowserApp.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/state/AppReducers.ts
  src/domain/app/state/AppStore.ts
  src/domain/app/types/AppTypes.ts
  src/domain/app/types/stateTypes.ts
  src/domain/auth/authenticate.ts
  src/domain/auth/constants/BackendAuthenticationActionConstants.ts
  src/domain/auth/getAuthenticatedUser.ts
  src/domain/auth/route/PrivateRoute.tsx
  src/domain/auth/state/AuthenticationReducers.ts
  src/domain/auth/state/AuthenticationSelectors.ts
  src/domain/auth/state/BackendAuthenticationActions.ts
  src/domain/auth/state/BackendAuthenticationReducer.ts
  src/domain/auth/state/authSelectors.ts
  src/domain/auth/types/BackendAuthenticationTypes.ts
  src/domain/auth/userManager.ts
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/state/RegistrationSelectors.ts
  yarn.lock
Labels: enhancement

#27 KK-49 | Prepopulate fields on frontpage form is user has submitted it before
  package.json
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/HomePreliminaryFormUtils.ts
  src/domain/home/form/types/HomeFormTypes.ts
  yarn.lock
Labels: enhancement

#28 KK-78 | Add language switch
  package.json
  src/assets/icons/svg/HelsinkiLogo.svg
  src/assets/icons/svg/person.svg
  src/assets/styles/variables.scss
  src/common/components/form/__tests__/validationUtils.tests.tsx
  src/common/components/form/fields/input/InputField.tsx
  src/common/components/form/fields/select/SelectField.tsx
  src/common/components/form/fields/select/__tests__/__snapshots__/SelectField.test.tsx.snap
  src/common/components/form/validationUtils.tsx
  src/common/components/icon/Icon.tsx
  src/common/components/icon/icon.module.scss
  src/common/components/select/Select.tsx
  src/common/components/select/select.module.scss
  src/common/route/RouteUtils.ts
  src/common/translation/TranslationConstants.ts
  src/common/translation/TranslationUtils.ts
  src/common/translation/i18n/i18nInit.ts
  src/common/translation/utils.tsx
  src/domain/app/App.tsx
  src/domain/app/BrowserApp.tsx
  src/domain/app/__tests__/BrowserApp.test.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/footer/Footer.tsx
  src/domain/app/header/Header.tsx
  src/domain/app/header/__tests__/Header.test.tsx
  src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap
  src/domain/app/header/header.module.scss
  src/domain/app/header/navbar/Navbar.tsx
  src/domain/app/header/navbar/languageDropdown/LanguageDropdown.tsx
  src/domain/app/header/navbar/languageDropdown/languageDropdown.module.scss
  src/domain/app/header/navbar/navbar.module.scss
  src/domain/app/layout/__tests__/Layout.test.tsx
  src/domain/app/layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/domain/auth/OidcCallback.tsx
  src/domain/auth/route/PrivateRoute.tsx
  src/domain/auth/route/__tests__/PrivateRoute.test.tsx
  src/domain/auth/state/AuthenticationSelectors.ts
  src/domain/auth/state/BackendAuthenticationReducer.ts
  src/domain/home/Home.tsx
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
  src/domain/home/form/partial/BirthdayFormField.tsx
  src/domain/home/form/partial/__tests__/__snapshots__/BirthdayFormField.test.tsx.snap
  src/domain/notFound/NotFound.tsx
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/index.tsx
  src/setupTests.ts
  yarn.lock
Labels: bug, enhancement

#29 KK-49 | Redirect to registration form after submitting homepage form
  src/domain/app/BrowserApp.tsx
  src/domain/app/header/navbar/Navbar.tsx
  src/domain/auth/OidcCallback.tsx
  src/domain/auth/authenticate.ts
  src/domain/home/__tests__/Home.test.tsx
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/__test__/HomePreliminaryForm.test.tsx
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
Labels: enhancement

#30 Change Docker setup to match infra, add deployment pipeline
  .dockerignore
  .env
  .env.development
  .gitlab-ci.yml
  .prod/nginx.conf
  Dockerfile
  docker-compose.yml
  src/domain/api/client.ts
Labels: enhancement

#32 KK-78 | Add login logout button as well as redirection
  src/assets/icons/svg/angleDown.svg
  src/common/components/dropdown/Dropdown.tsx
  src/common/components/dropdown/dropdown.module.scss
  src/common/components/select/select.module.scss
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/BrowserApp.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/navbar/Navbar.tsx
  src/domain/app/header/navbar/__tests__/Navbar.test.tsx
  src/domain/app/header/navbar/__tests__/__snapshots__/Navbar.test.tsx.snap
  src/domain/app/header/navbar/languageDropdown/languageDropdown.module.scss
  src/domain/app/header/navbar/navbar.module.scss
  src/domain/app/header/userDropdown/UserDropdown.tsx
  src/domain/app/header/userDropdown/userDropdown.module.scss
  src/domain/auth/authenticate.ts
  src/domain/auth/state/AuthenticationSelectors.ts
  src/domain/auth/userManager.ts
  src/domain/home/form/HomePreliminaryForm.tsx
Labels: enhancement

#33 KK-29 | Refactor birthday into birthdate
  src/common/components/form/__tests__/validationUtils.tests.tsx
  src/common/components/form/validationUtils.tsx
  src/common/time/TimeConstants.ts
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/HomePreliminaryFormUtils.ts
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
  src/domain/home/form/partial/BirthdateFormField.tsx
  src/domain/home/form/partial/__tests__/BirthdateFormField.test.tsx
  src/domain/home/form/partial/__tests__/__snapshots__/BirthdateFormField.test.tsx.snap
  src/domain/home/form/partial/__tests__/__snapshots__/BirthdayFormField.test.tsx.snap
  src/domain/home/form/partial/birthdateFormField.module.scss
  src/domain/home/form/types/HomeFormTypes.ts
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/state/RegistrationReducers.tsx
  src/domain/registration/types/RegistrationTypes.ts
Labels: bug

#31 KK-29 | Submit registration form data as mutation query
  package.json
  src/common/time/TimeConstants.ts
  src/common/time/utils.tsx
  src/domain/api/__tests__/client.test.ts
  src/domain/api/client.ts
  src/domain/auth/state/AuthenticationSelectors.ts
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/HomePreliminaryFormUtils.ts
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/RegistrationForm.test.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/mutations/submitChild.ts
  yarn.lock
Labels: enhancement

#35 KK-49 | Fetch & name from profile for registration form
  .env
  README.md
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/RegistrationFormSelectors.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/state/RegistrationReducers.tsx
  src/domain/registration/types/RegistrationTypes.ts
Labels: enhancement

#36 Add test for HomePreliminaryFormUtils
  src/domain/home/form/__test__/HomePreliminaryFormUtils.test.ts
Labels: enhancement

#39 KK-91 | HomeForm fixes
  src/assets/icons/svg/checkbox.svg
  src/assets/styles/colors.scss
  src/assets/styles/variables.scss
  src/common/components/form/fields/input/InputField.tsx
  src/common/components/input/Checkbox.tsx
  src/common/components/input/__tests__/Checkbox.test.tsx
  src/common/components/input/__tests__/__snapshots__/Checkbox.test.tsx.snap
  src/common/components/input/input.module.scss
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
  src/domain/home/form/homePreliminaryForm.module.scss
  src/domain/home/form/partial/BirthdateFormField.tsx
  src/domain/home/form/partial/__tests__/__snapshots__/BirthdateFormField.test.tsx.snap
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
Labels: enhancement

#38 KK-107 | Show a message that a child is not eligible if the child is too old or lives outside Helsinki
  .env
  README.md
  src/common/components/form/__tests__/validationUtils.tests.tsx
  src/common/components/form/validationUtils.tsx
  src/common/time/TimeConstants.ts
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/App.tsx
  src/domain/app/notFound/NotFound.tsx
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/registration/notEligible/NotEligible.tsx
  src/domain/registration/notEligible/NotEligibleUtils.ts
  src/domain/registration/notEligible/__tests__/NotEligible.test.tsx
  src/domain/registration/notEligible/__tests__/NotEligibleUtils.test.ts
  src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap
  src/domain/registration/notEligible/notEligible.module.scss
Labels: enhancement

#40 Show child is not eligible page if child is not eligible
  src/domain/home/form/HomePreliminaryForm.tsx
Labels: bug

#41 KK-105 | New welcome component to show after successful registration
  src/assets/icons/svg/adultFace.svg
  src/assets/icons/svg/tada.svg
  src/common/components/icon/Icon.tsx
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/App.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/welcome/Welcome.tsx
  src/domain/registration/welcome/__tests__/Welcome.test.tsx
  src/domain/registration/welcome/__tests__/__snapshots__/Welcome.test.tsx.snap
  src/domain/registration/welcome/welcome.module.scss
Labels: enhancement

#42 KK-91 | Registration form fix
  src/assets/styles/variables.scss
  src/common/components/dropdown/dropdown.module.scss
  src/common/components/form/fields/input/EnhancedInputField.tsx
  src/common/components/form/fields/input/__tests__/EnhancedInputField.test.tsx
  src/common/components/form/fields/select/SelectField.tsx
  src/common/components/form/fields/select/__tests__/__snapshots__/SelectField.test.tsx.snap
  src/common/components/form/fields/select/select.module.scss
  src/common/components/icon/icon.module.scss
  src/common/components/input/input.module.scss
  src/common/components/select/Select.tsx
  src/common/components/select/select.module.scss
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/navbar/languageDropdown/LanguageDropdown.tsx
  src/domain/app/header/navbar/languageDropdown/languageDropdown.module.scss
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
  src/domain/home/form/partial/BirthdateFormField.tsx
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/form/registrationForm.module.scss
  src/domain/registration/state/RegistrationReducers.tsx
  src/domain/registration/types/RegistrationTypes.ts
Labels: bug, enhancement

#44 Add icon to non eligible page
  src/assets/styles/mixins.scss
  src/common/components/icon/Icon.tsx
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/footer/footer.module.scss
  src/domain/home/form/homePreliminaryForm.module.scss
  src/domain/registration/form/registrationForm.module.scss
  src/domain/registration/notEligible/NotEligible.tsx
  src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap
  src/domain/registration/notEligible/notEligible.module.scss
Labels: enhancement

#45 KK-119 render children list
  src/domain/child/types/ChildTypes.ts
  src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/HomePreliminaryFormUtils.ts
  src/domain/home/form/__test__/HomePreliminaryFormUtils.test.ts
  src/domain/registration/constants/RegistrationActionConstants.tsx
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/form/partial/ChildFormField.tsx
  src/domain/registration/form/partial/childFormField.module.scss
  src/domain/registration/notEligible/NotEligibleUtils.ts
  src/domain/registration/notEligible/__tests__/NotEligibleUtils.test.ts
  src/domain/registration/state/RegistrationActions.tsx
  src/domain/registration/state/RegistrationReducers.tsx
  src/domain/registration/types/RegistrationTypes.ts
  src/domain/registration/welcome/welcome.module.scss
Labels: enhancement

#47 KK-118 | Multiple child support modal
  package.json
  src/assets/icons/svg/close.svg
  src/assets/icons/svg/delete.svg
  src/assets/icons/svg/happyChild.svg
  src/assets/styles/variables.scss
  src/common/components/modal/Modal.tsx
  src/common/components/modal/__tests__/Modal.test.tsx
  src/common/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap
  src/common/components/modal/modal.module.scss
  src/common/test/testUtils.tsx
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/child/constants/ChildRelationshipConstants.ts
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/child/modal/__tests__/ChildFormModal.test.tsx
  src/domain/child/modal/__tests__/__snapshots__/ChildFormModal.test.tsx.snap
  src/domain/child/modal/childFormModal.module.scss
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/partial/BirthdateFormField.tsx
  src/domain/home/form/partial/__tests__/__snapshots__/BirthdateFormField.test.tsx.snap
  src/domain/registration/constants/RegistrationActionConstants.tsx
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/RegistrationForm.test.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/form/partial/ChildFormField.tsx
  src/domain/registration/form/partial/childFormField.module.scss
  src/domain/registration/form/registrationForm.module.scss
  src/domain/registration/modal/AddNewChildFormModal.tsx
  src/domain/registration/modal/__tests__/AddNewChildFormModal.test.tsx
  src/domain/registration/modal/__tests__/__snapshots__/AddNewChildFormModal.test.tsx.snap
  src/domain/registration/state/RegistrationActions.tsx
  src/domain/registration/state/RegistrationReducers.tsx
  src/domain/registration/state/RegistrationSelectors.ts
  src/index.tsx
  yarn.lock
Labels: enhancement

#49 change react app url to test env kukku
  .gitlab-ci.yml
Labels: enhancement

#46 KK-98 | Add first iteration of profile page
  package.json
  src/assets/icons/svg/envelopeWithStars.svg
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/api/__tests__/client.test.ts
  src/domain/api/generatedTypes/ChildrenQuery.ts
  src/domain/api/generatedTypes/DummyQuery.ts
  src/domain/api/generatedTypes/GuardiansQuery.ts
  src/domain/api/generatedTypes/globalTypes.ts
  src/domain/api/generatedTypes/profileQuery.ts
  src/domain/api/generatedTypes/submitChild.ts
  src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
  src/domain/app/App.tsx
  src/domain/app/state/AppReducers.ts
  src/domain/auth/OidcCallback.tsx
  src/domain/auth/authenticate.ts
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/child/queries/ChildQueries.ts
  src/domain/child/types/ChildTypes.ts
  src/domain/guardian/queries/GuardianQueries.ts
  src/domain/guardian/types/GuardianTypes.ts
  src/domain/profile/Profile.tsx
  src/domain/profile/ProfileUtils.ts
  src/domain/profile/__tests__/Profile.test.tsx
  src/domain/profile/__tests__/__snapshots__/Profile.test.tsx.snap
  src/domain/profile/components/noUpcomingEvents/NoUpcomingEvents.tsx
  src/domain/profile/constants/ProfileActionConstants.tsx
  src/domain/profile/profile.module.scss
  src/domain/profile/queries/ProfileQuery.ts
  src/domain/profile/state/ProfileActions.tsx
  src/domain/profile/state/ProfileReducers.tsx
  src/domain/profile/state/ProfileSelectors.ts
  src/domain/profile/type/ProfileTypes.ts
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts
  src/domain/registration/welcome/Welcome.tsx
  src/domain/registration/welcome/__tests__/__snapshots__/Welcome.test.tsx.snap
Labels: enhancement

#48 KK-122 | Translate child-guardian relationship labels
  src/domain/child/ChildUtils.ts
  src/domain/child/constants/ChildRelationshipConstants.ts
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/form/partial/ChildFormField.tsx
Labels: enhancement
