Repository City-of-Helsinki/kukkuu-ui, pull requests merged in 2020-02, with the labels that each got.

#139 KK-239 | Prevent horizontal scrolling/overflow on mobile
  src/common/components/input/input.module.scss
Labels: bug

#149 Update develop
  CHANGELOG.md
  package.json
Labels: enhancement

#150 KK-244 | Submit button should alway clickable
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
  src/domain/registration/form/RegistrationForm.tsx
Labels: enhancement

#153 KK-214 | Use fully qualified url for og:image and twitter:image
  public/index.html
Labels: bug

#154 KK-215 | Add usage analytics
  public/index.html
  src/common/components/dropdown/Dropdown.tsx
  src/domain/app/BrowserApp.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/userDropdown/UserDropdown.tsx
  src/domain/app/header/userMenu/UserMenu.tsx
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/registration/form/RegistrationForm.tsx
Labels: enhancement

#155 Release v0.1.2
  .travis.yml
  CHANGELOG.md
  package.json
  public/index.html
  src/common/components/dropdown/Dropdown.tsx
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/domain/app/BrowserApp.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/userDropdown/UserDropdown.tsx
  src/domain/app/header/userMenu/UserMenu.tsx
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
  src/domain/registration/form/RegistrationForm.tsx
Labels: release

#156 master to develop
  CHANGELOG.md
  package.json
Labels: release

#151 KK-222 | Display user session timeout prompt when token expired.
  CHANGELOG.md
  package.json
  src/common/components/modal/Modal.tsx
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/api/__tests__/client.test.ts
  src/domain/api/client.ts
  src/domain/app/App.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/userDropdown/UserDropdown.tsx
  src/domain/app/sessionPrompt/SessionPrompt.tsx
  src/domain/app/sessionPrompt/sessionPrompt.module.scss
  src/domain/app/state/AppReducers.ts
  src/domain/app/state/AppStore.ts
  src/domain/app/state/ui/UIActions.ts
  src/domain/app/state/ui/UIActionsConstants.ts
  src/domain/app/state/ui/UIReducers.ts
  src/domain/app/state/ui/UISelectors.ts
  src/domain/app/types/ui/UITypes.ts
  src/domain/auth/authenticate.ts
  src/domain/auth/constants/BackendAuthenticationActionConstants.ts
  src/domain/auth/state/AuthenticationSelectors.ts
  src/domain/auth/state/AuthenticationUtils.ts
  src/domain/auth/state/BackendAuthenticationActions.ts
  src/domain/auth/state/BackendAuthenticationReducer.ts
  src/domain/auth/types/BackendAuthenticationTypes.ts
  src/domain/child/mutation/ChildMutation.ts
  src/domain/child/queries/ChildQueries.ts
  src/domain/guardian/queries/GuardianQueries.ts
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/profile/__tests__/__snapshots__/Profile.test.tsx.snap
  src/domain/profile/queries/ProfileQuery.ts
  src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts
  src/domain/registration/welcome/__tests__/__snapshots__/Welcome.test.tsx.snap
  yarn.lock
Labels: bug, enhancement

#158 Fix docker build missing dependencies
  .travis.yml
  CHANGELOG.md
  package.json
  yarn.lock
Labels: bug

#157 KK-262 | Show guardian info on profile page
  src/assets/icons/svg/envelope.svg
  src/assets/icons/svg/gear.svg
  src/assets/icons/svg/homeKid.svg
  src/assets/icons/svg/homeTheater.svg
  src/domain/app/App.tsx
  src/domain/profile/Profile.tsx
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/profile/children/child/ProfileChildDetail.tsx
  src/domain/profile/children/profileChildrenList.module.scss
  src/domain/profile/profile.module.scss
  src/domain/profile/route/ProfileRoute.tsx
Labels: enhancement

#159 KK-123 | Add child edit information button
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/profile/children/child/ProfileChildDetail.tsx
  src/domain/profile/children/child/modal/profileChildDetailEditModal.module.scss
  src/domain/profile/children/child/profileChildDetail.module.scss
Labels: enhancement

#161 KK-123 | Add edit child modal
  src/domain/api/client.ts
  src/domain/child/ChildConstants.ts
  src/domain/child/ChildUtils.ts
  src/domain/child/__tests__/ChildUtils.test.ts
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/child/modal/__tests__/__snapshots__/ChildFormModal.test.tsx.snap
  src/domain/home/form/HomePreliminaryFormUtils.ts
  src/domain/home/form/__test__/HomePreliminaryFormUtils.test.ts
  src/domain/profile/children/child/ProfileChildDetail.tsx
  src/domain/profile/children/child/modal/ProfileChildDetailEditModal.tsx
  src/domain/registration/modal/AddNewChildFormModal.tsx
Labels: enhancement

#162 KK-262 | Add modal and mutation to edit guardian's information
  src/assets/icons/svg/gear.svg
  src/common/components/modal/modal.module.scss
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/api/generatedTypes/globalTypes.ts
  src/domain/api/generatedTypes/updateMyProfile.ts
  src/domain/profile/Profile.tsx
  src/domain/profile/children/child/ProfileChildDetail.tsx
  src/domain/profile/children/child/profileChildDetail.module.scss
  src/domain/profile/modal/EditProfileModal.tsx
  src/domain/profile/modal/__tests__/EditProfileModal.test.tsx
  src/domain/profile/modal/__tests__/__snapshots__/EditProfileModal.test.tsx.snap
  src/domain/profile/modal/editProfileModal.module.scss
  src/domain/profile/mutations/updateMyProfileMutation.ts
  src/domain/profile/profile.module.scss
Labels: enhancement

#163 KK-123 | Add edit and delete child mutation
  src/common/components/modal/modal.module.scss
  src/common/components/select/Select.tsx
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/api/__tests__/client.test.ts
  src/domain/api/generatedTypes/childByIdQuery.ts
  src/domain/api/generatedTypes/deleteChild.ts
  src/domain/api/generatedTypes/globalTypes.ts
  src/domain/api/generatedTypes/profileQuery.ts
  src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
  src/domain/api/generatedTypes/updateChild.ts
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/child/modal/childFormModal.module.scss
  src/domain/child/mutation/ChildMutation.ts
  src/domain/child/queries/ChildQueries.ts
  src/domain/home/Home.tsx
  src/domain/profile/ProfileUtil.ts
  src/domain/profile/__tests__/ProfileUtils.test.ts
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/profile/children/child/ProfileChildDetail.tsx
  src/domain/profile/children/child/modal/ProfileChildDetailEditModal.tsx
  src/domain/profile/children/profileChildrenList.module.scss
  src/domain/profile/modal/EditProfileModal.tsx
Labels: enhancement

#164 KK-263 | Add Dot and remove Oodi as partners, shrink svg icons
  src/assets/icons/partners/dotdot.png
  src/assets/icons/partners/oodihelsinki.png
  src/assets/icons/svg/adultFace.svg
  src/assets/icons/svg/adultFaceHappy.svg
  src/assets/icons/svg/angleDown.svg
  src/assets/icons/svg/arrowLeft.svg
  src/assets/icons/svg/birthdayCake.svg
  src/assets/icons/svg/checkbox.svg
  src/assets/icons/svg/childFaceHappy.svg
  src/assets/icons/svg/close.svg
  src/assets/icons/svg/closeWithoutCircle.svg
  src/assets/icons/svg/delete.svg
  src/assets/icons/svg/envelopeWithStars.svg
  src/assets/icons/svg/hamburgerMenu.svg
  src/assets/icons/svg/homeTheater.svg
  src/assets/icons/svg/homeTicket.svg
  src/assets/icons/svg/mobile.svg
  src/assets/icons/svg/person.svg
  src/assets/icons/svg/tada.svg
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/home/partners/__tests__/__snapshots__/Partners.test.tsx.snap
  src/domain/home/partners/constants/PartnersConstants.tsx
Labels: enhancement

#167 KK-123 | delete child prompt
  CHANGELOG.md
  src/assets/styles/main.scss
  src/assets/styles/variables.scss
  src/common/components/modal/Modal.tsx
  src/common/components/modal/modal.module.scss
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/sessionPrompt/sessionPrompt.module.scss
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/child/modal/__tests__/__snapshots__/ChildFormModal.test.tsx.snap
  src/domain/child/modal/childFormModal.module.scss
  src/domain/child/modal/prompt/delete/ChildFormModalDeletePrompt.tsx
  src/domain/child/modal/prompt/delete/childFormModalDeletePrompt.module.scss
  src/domain/child/modal/prompt/nonEligible/ChildFormModalNonEligible.tsx
  src/domain/child/modal/prompt/nonEligible/childFormModalNonEligible.module.scss
  src/domain/home/form/homePreliminaryForm.module.scss
  src/domain/home/hero/hero.module.scss
  src/domain/home/instructions/homeInstructions.module.scss
  src/domain/profile/children/child/profileChildDetail.module.scss
  src/domain/profile/children/profileChildrenList.module.scss
  src/domain/profile/events/profileNoEvent.module.scss
  src/domain/profile/profile.module.scss
  src/domain/registration/form/partial/childFormField.module.scss
  src/domain/registration/form/registrationForm.module.scss
Labels: enhancement

#169 KK-215 | Improve analytics
  package.json
  public/index.html
  src/domain/app/BrowserApp.tsx
  src/domain/app/header/userDropdown/UserDropdown.tsx
  src/domain/app/layout/PageWrapper.tsx
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/profile/modal/EditProfileModal.tsx
  src/domain/registration/notEligible/NotEligible.tsx
  src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap
  yarn.lock
Labels: enhancement

#172 KK-123 | Adjustments for small screens and modal fixes
  CHANGELOG.md
  src/assets/styles/variables.scss
  src/common/components/modal/Modal.tsx
  src/common/components/modal/modal.module.scss
  src/domain/child/modal/childFormModal.module.scss
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/profile/children/child/profileChildDetail.module.scss
  src/domain/profile/children/profileChildrenList.module.scss
  src/domain/profile/modal/editProfileModal.module.scss
  src/domain/profile/profile.module.scss
Labels: enhancement

#170 Change the MFA logo
  src/assets/icons/partners/mfa.png
Labels: enhancement

#176 KK-123 | Align child icon with first line of child name
  src/domain/profile/children/child/profileChildDetail.module.scss
Labels: enhancement

#175 Bumping dependencies
  .travis.yml
  CHANGELOG.md
  package.json
  yarn.lock
Labels: dependencies

#180 Send environment info to sentry, only track analytics from production
  .gitlab-ci.yml
  src/domain/app/BrowserApp.tsx
  src/index.tsx
Labels: enhancement

#181 KK-250 | Ensure that login page is in user's chosen language
  CHANGELOG.md
  src/domain/auth/authenticate.ts
Labels: enhancement

#182 Display raw username
  CHANGELOG.md
  src/domain/profile/children/child/profileChild.module.scss
  src/domain/profile/children/child/profileChildDetail.module.scss
  src/domain/profile/profile.module.scss
Labels: enhancement

#183 KK-276 | New invitation button on children list
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/profile/children/child/ProfileChild.tsx
  src/domain/profile/children/child/profileChild.module.scss
Labels: enhancement

#185 KK-276 | Show invitation label on child when enrolment is possible
  src/domain/api/generatedTypes/ChildrenQuery.ts
  src/domain/api/generatedTypes/GuardiansQuery.ts
  src/domain/api/generatedTypes/addNewChild.ts
  src/domain/api/generatedTypes/childByIdQuery.ts
  src/domain/api/generatedTypes/deleteChild.ts
  src/domain/api/generatedTypes/globalTypes.ts
  src/domain/api/generatedTypes/profileQuery.ts
  src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
  src/domain/api/generatedTypes/updateChild.ts
  src/domain/api/generatedTypes/updateMyProfile.ts
  src/domain/profile/children/child/ProfileChild.tsx
  src/domain/profile/queries/ProfileQuery.ts
  src/domain/profile/state/ProfileActions.tsx
Labels: enhancement

#187 KK-265 | Update readme
  CONTRIBUTING.md
  README.md
  src/domain/app/BrowserApp.tsx
Labels: documentation

#186 KK-299 | RFC: Event page version 0.0.1
  src/assets/styles/variables.scss
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/api/client.ts
  src/domain/api/generatedTypes/eventQuery.ts
  src/domain/api/generatedTypes/globalTypes.ts
  src/domain/app/App.tsx
  src/domain/app/header/navbar/navbar.module.scss
  src/domain/event/Event.tsx
  src/domain/event/EventOccurrence.tsx
  src/domain/event/EventOccurrenceList.tsx
  src/domain/event/event.module.scss
  src/domain/event/eventOccurrence.module.scss
  src/domain/event/eventOccurrenceList.module.scss
  src/domain/event/queries/eventQuery.ts
  src/domain/event/route/EventRoute.tsx
Labels: enhancement

#188 KK-299 | Add tests for event components
  src/domain/api/client.ts
  src/domain/event/Event.tsx
  src/domain/event/__tests__/EventOccurrence.test.tsx
  src/domain/event/__tests__/EventOccurrenceList.test.tsx
  src/domain/event/__tests__/__snapshots__/EventOccurrence.test.tsx.snap
  src/domain/event/__tests__/__snapshots__/EventOccurrenceList.test.tsx.snap
  src/setupTests.ts
Labels: enhancement
