Repository City-of-Helsinki/kukkuu-ui, pull requests merged in 2020-01, with the labels that each got.

#92 Feature/kk 158 on the front page the background colors should go from edge to edge
  .gitignore
  src/domain/app/layout/Container.tsx
  src/domain/app/layout/__tests__/Container.test.tsx
  src/domain/app/layout/__tests__/__snapshots__/Container.test.tsx.snap
  src/domain/app/layout/container.module.scss
  src/domain/home/Home.tsx
  src/domain/home/contact/homeContact.module.scss
  src/domain/home/home.module.scss
  src/domain/home/instructions/homeInstructions.module.scss
  src/domain/home/partners/HomePartners.tsx
  src/domain/home/partners/__tests__/__snapshots__/Partners.test.tsx.snap
  src/domain/home/partners/homePartners.module.scss
Labels: enhancement

#95 KK-187 | Replace deprecated redux-starter-kit with redux-tooltip
  package.json
  src/domain/app/state/AppReducers.ts
  src/domain/app/state/AppStore.ts
  src/domain/app/types/AppTypes.ts
  src/domain/auth/authenticate.ts
  src/domain/auth/state/BackendAuthenticationActions.ts
  src/domain/auth/state/BackendAuthenticationReducer.ts
  src/domain/profile/state/ProfileActions.tsx
  src/domain/profile/state/ProfileReducers.tsx
  src/domain/registration/state/RegistrationActions.tsx
  src/domain/registration/state/RegistrationReducers.tsx
  yarn.lock
Labels: dependencies

#97 Fix custom birthdate validation not getting translated
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/auth/state/BackendAuthenticationActions.ts
  src/domain/home/form/partial/BirthdateFormField.tsx
Labels: bug

#98 KK-188 | use maxLength to limit amount of char in input number
  src/common/components/form/fields/input/NumberInputField.tsx
  src/domain/home/form/partial/BirthdateFormField.tsx
Labels: enhancement

#94 KK-159 | Front page hero header text should not be on top of kids change kids image
  src/assets/icons/svg/Culture_kids@2x.png
  src/assets/icons/svg/Culture_kids_background@2x.png
  src/assets/icons/svg/kids.png
  src/assets/styles/layout.scss
  src/domain/home/contact/homeContact.module.scss
  src/domain/home/hero/HomeHero.tsx
  src/domain/home/hero/hero.module.scss
  src/domain/home/instructions/homeInstructions.module.scss
  src/domain/home/partners/homePartners.module.scss
Labels: enhancement

#105 KK-192 | Upgrade typescript and CRA, fix security warnings.
  package.json
  src/domain/app/BrowserApp.tsx
  src/domain/app/layout/PageLayout.tsx
  src/domain/app/layout/__tests__/Layout.test.tsx
  src/domain/app/layout/pageLayout.module.scss
  yarn.lock
Labels: dependencies

#106 KK-133 | implement 404 page follow new design
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/notFound/NotFound.tsx
  src/domain/app/notFound/notFound.module.scss
Labels: enhancement

#107 KK-193 | Favicon
  package.json
  public/browserconfig.xml
  public/favicon.ico
  public/images/android-chrome-192x192.png
  public/images/android-chrome-512x512.png
  public/images/apple-touch-icon.png
  public/images/favicon-16x16.png
  public/images/favicon-32x32.png
  public/images/mstile-150x150.png
  public/index.html
  public/manifest.json
  src/assets/styles/colors.scss
  src/domain/app/footer/footer.module.scss
  src/domain/app/layout/container.module.scss
  src/domain/app/notFound/notFound.module.scss
  src/domain/home/contact/HomeContact.tsx
  src/domain/home/contact/homeContact.module.scss
  src/domain/home/partners/partnerLogoList.module.scss
  yarn.lock
Labels: enhancement

#103 Add Tunnistamo logout
  src/domain/app/header/userDropdown/UserDropdown.tsx
  src/domain/auth/authenticate.ts
Labels: enhancement

#108 KK-174 | Ensure to toggle off nonEligible hook state when close modal
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/child/modal/__tests__/__snapshots__/ChildFormModal.test.tsx.snap
Labels: bug

#109 U se optinal chaining from latest typescript
  .vscode/settings.json
  package.json
  src/domain/app/App.tsx
  src/domain/home/form/HomePreliminaryForm.tsx
  src/domain/profile/ProfileUtils.ts
  src/domain/registration/form/RegistrationForm.tsx
  yarn.lock
Labels: enhancement

#111 KK-202 | Use HDS variables to override default styles
  package.json
  src/assets/styles/main.scss
  src/assets/styles/vendor/_normalize.scss
  src/common/components/select/select.module.scss
  src/common/translation/TranslationConstants.ts
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/navbar/navbar.module.scss
  src/index.tsx
  yarn.lock
Labels: enhancement

#113 KK-190 | Hide login button when user is already authenticated
  src/domain/home/Home.tsx
  src/domain/home/hero/HomeHero.tsx
Labels: bug

#114 KK-197 | Add Accessibility statement
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/accessibilityStatement/AccessibilityStatement.tsx
  src/domain/accessibilityStatement/AccessibilityStatementEn.tsx
  src/domain/accessibilityStatement/AccessibilityStatementFi.tsx
  src/domain/accessibilityStatement/AccessibilityStatementSv.tsx
  src/domain/accessibilityStatement/__tests__/AccessibilityStatement.test.tsx
  src/domain/accessibilityStatement/__tests__/AccessibilityStatementFi.test.tsx
  src/domain/accessibilityStatement/__tests__/__snapshots__/AccessibilityStatement.test.tsx.snap
  src/domain/accessibilityStatement/__tests__/__snapshots__/AccessibilityStatementFi.test.tsx.snap
  src/domain/accessibilityStatement/accessibilityStatement.module.scss
  src/domain/app/App.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/footer/Footer.tsx
  src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/domain/app/footer/footer.module.scss
Labels: enhancement

#112 KK-203 | Use real typing than overrided types for Profile
  src/domain/home/form/HomePreliminaryFormUtils.ts
  src/domain/profile/CheckHasProfile.tsx
  src/domain/profile/Profile.tsx
  src/domain/profile/ProfileUtils.ts
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/profile/children/child/ProfileChildDetail.tsx
  src/domain/profile/state/ProfileReducers.tsx
  src/domain/profile/state/ProfileSelectors.ts
  src/domain/profile/type/ProfileTypes.ts
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/__tests__/RegistrationForm.test.tsx
  src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
  src/domain/registration/state/RegistrationActions.tsx
  src/domain/registration/welcome/Welcome.tsx
  src/domain/registration/welcome/welcome.module.scss
Labels: bug, enhancement

#115 KK-171 | Accessibility improvements
  src/assets/styles/main.scss
  src/assets/styles/mixins.scss
  src/assets/styles/variables.scss
  src/common/components/button/button.module.scss
  src/common/components/form/fields/input/EnhancedInputField.tsx
  src/common/components/form/fields/input/__tests__/__snapshots__/EnhancedInputField.test.tsx.snap
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/home/form/partial/__tests__/__snapshots__/BirthdateFormField.test.tsx.snap
  src/domain/profile/children/child/profileChild.module.scss
  src/domain/profile/children/profileChildrenList.module.scss
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/partial/ChildFormField.tsx
Labels: enhancement

#116 KK-205 | Add postalCode as required field
  apollo.config.js
  src/common/components/form/__tests__/validationUtils.tests.tsx
  src/common/components/form/validationUtils.tsx
  src/domain/api/generatedTypes/globalTypes.ts
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/registration/form/partial/ChildFormField.tsx
Labels: enhancement

#117 KK-206 | Only allow children born in 2020 to register
  src/common/time/TimeConstants.ts
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/domain/registration/notEligible/NotEligibleUtils.ts
  src/domain/registration/notEligible/__tests__/NotEligibleUtils.test.ts
Labels: enhancement

#118 KK-172 | Add link to Description of the file/Rekisteriseloste/Registerbeskrivning
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/footer/Footer.tsx
  src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/domain/app/footer/footer.module.scss
Labels: enhancement

#119 KK-175 | add validation for child birthdate modal
  package.json
  src/common/test/TestForm.tsx
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/home/form/partial/BirthdateFormField.tsx
  yarn.lock
Labels: bug

#120 KK-214 | Add translatable title&meta-description and image for social sharing
  .gitlab-ci.yml
  public/images/kummilapsi-og-image.jpg
  public/index.html
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/navbar/languageBar/LanguageBar.tsx
  src/domain/app/layout/PageWrapper.tsx
  src/domain/app/layout/__tests__/__snapshots__/PageWrapper.test.tsx.snap
Labels: bug, enhancement

#122 KK-156 | Accessibility improvements
  public/index.html
  src/common/components/button/Button.tsx
  src/common/components/button/button.module.scss
  src/common/components/dropdown/Dropdown.tsx
  src/common/components/icon/Icon.tsx
  src/common/components/modal/Modal.tsx
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/header/navbar/Navbar.tsx
  src/domain/app/header/navbar/__tests__/__snapshots__/Navbar.test.tsx.snap
  src/domain/app/header/navbar/navbar.module.scss
  src/domain/app/header/navbar/smallScreenNav/SmallScreenNav.tsx
  src/domain/app/layout/PageWrapper.tsx
  src/domain/app/layout/__tests__/__snapshots__/PageWrapper.test.tsx.snap
  src/domain/app/notFound/NotFound.tsx
  src/domain/child/modal/ChildFormModal.tsx
  src/domain/home/instructions/HomeInstructions.tsx
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/profile/children/child/ProfileChild.tsx
  src/domain/profile/children/child/ProfileChildDetail.tsx
  src/domain/profile/events/ProfileNoEvent.tsx
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/partial/ChildFormField.tsx
  src/domain/registration/notEligible/NotEligible.tsx
  src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap
  src/domain/registration/welcome/Welcome.tsx
Labels: enhancement

#126 Auto fix prettier all scss file
  package.json
  src/assets/styles/layout.scss
  src/common/components/dropdown/dropdown.module.scss
  src/common/components/form/fields/input/inputField.module.scss
  src/common/components/form/fields/select/select.module.scss
  src/common/components/icon/icon.module.scss
  src/common/components/input/input.module.scss
  src/common/components/modal/modal.module.scss
  src/common/components/spinner/loadingSpinner.module.scss
  src/domain/app/header/header.module.scss
  src/domain/app/header/navbar/languageBar/languageBar.module.scss
  src/domain/app/header/navbar/languageDropdown/languageDropdown.module.scss
  src/domain/app/header/navbar/smallScreenNav/smallScreenNav.module.scss
  src/domain/app/header/userMenu/userMenu.module.scss
  src/domain/app/layout/pageLayout.module.scss
  src/domain/app/layout/pageWrapper.module.scss
  src/domain/child/modal/childFormModal.module.scss
  src/domain/home/form/homePreliminaryForm.module.scss
  src/domain/home/form/partial/birthdateFormField.module.scss
  src/domain/home/home.module.scss
  src/domain/home/instructions/homeInstructions.module.scss
  src/domain/home/partners/homePartners.module.scss
  src/domain/profile/children/child/profileChildDetail.module.scss
  src/domain/profile/events/profileNoEvent.module.scss
  src/domain/profile/profile.module.scss
  src/domain/registration/form/partial/childFormField.module.scss
  src/domain/registration/form/registrationForm.module.scss
  src/domain/registration/notEligible/notEligible.module.scss
Labels: enhancement

#125 KK-162 | vertical margins
  src/assets/styles/mixins.scss
  src/assets/styles/variables.scss
  src/common/components/form/fields/input/inputField.module.scss
  src/common/components/input/input.module.scss
  src/common/components/modal/modal.module.scss
  src/common/components/select/select.module.scss
  src/domain/child/modal/childFormModal.module.scss
  src/domain/home/contact/homeContact.module.scss
  src/domain/home/form/homePreliminaryForm.module.scss
  src/domain/home/hero/hero.module.scss
  src/domain/home/instructions/homeInstructions.module.scss
  src/domain/home/partners/homePartners.module.scss
  src/domain/profile/children/child/profileChild.module.scss
  src/domain/profile/children/child/profileChildDetail.module.scss
  src/domain/profile/children/profileChildrenList.module.scss
  src/domain/profile/events/profileNoEvent.module.scss
  src/domain/registration/form/RegistrationForm.tsx
  src/domain/registration/form/partial/childFormField.module.scss
  src/domain/registration/form/registrationForm.module.scss
Labels: enhancement

#127 KK-214 | Add more og tags and twitter card
  public/index.html
Labels: enhancement

#130 KK-162 | Extra style reviews
  src/assets/icons/svg/closeWithoutCircle.svg
  src/assets/styles/main.scss
  src/common/components/modal/Modal.tsx
  src/common/components/modal/modal.module.scss
  src/domain/app/layout/PageWrapper.tsx
  src/domain/app/layout/__tests__/__snapshots__/PageWrapper.test.tsx.snap
  src/domain/app/layout/pageLayout.module.scss
  src/domain/app/layout/pageWrapper.module.scss
  src/domain/home/Home.tsx
  src/domain/home/contact/homeContact.module.scss
  src/domain/home/home.module.scss
  src/domain/profile/children/child/profileChildDetail.module.scss
  src/domain/registration/form/partial/childFormField.module.scss
  src/domain/registration/form/registrationForm.module.scss
Labels: bug, enhancement

#129 Import the only library we use from lodash to shrink build size
  src/domain/child/ChildUtils.ts
Labels: enhancement

#131 KK-238 | Fix cached profile on Home doesnt get wiped when no token
  src/domain/app/App.tsx
  src/domain/app/__tests__/BrowserApp.test.tsx
  src/domain/home/Home.tsx
  src/domain/profile/CheckHasProfile.tsx
  src/domain/profile/Profile.tsx
  src/domain/profile/__tests__/CheckHasProfile.test.tsx
  src/domain/profile/__tests__/__snapshots__/CheckHasProfile.test.tsx.snap
  src/domain/profile/children/ProfileChildrenList.tsx
  src/domain/registration/form/RegistrationForm.tsx
Labels: bug

#132 KK-208 | Add Terms of Service page
  src/common/translation/i18n/en.json
  src/common/translation/i18n/fi.json
  src/common/translation/i18n/sv.json
  src/domain/app/App.tsx
  src/domain/app/__tests__/__snapshots__/BrowserApp.test.tsx.snap
  src/domain/app/footer/Footer.tsx
  src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/domain/termsOfService/TermsOfService.tsx
  src/domain/termsOfService/__tests__/TermsOfService.test.tsx
  src/domain/termsOfService/__tests__/__snapshots__/TermsOfService.test.tsx.snap
  src/domain/termsOfService/termsOfService.module.scss
Labels: enhancement

#137 add fetch profile in registration form
  src/domain/home/Home.tsx
  src/domain/registration/form/RegistrationForm.tsx
Labels: bug

#135 Reduce download size by running logo pngs through TinyPNG
  src/assets/icons/partners/amosrex.png
  src/assets/icons/partners/cirko.png
  src/assets/icons/partners/designmuseum.png
  src/assets/icons/partners/hamhelsinki.png
  src/assets/icons/partners/hel.png
  src/assets/icons/partners/helsinginkaupunginmuseo.png
  src/assets/icons/partners/helsinginkaupunginorkesteri.png
  src/assets/icons/partners/hkt.png
  src/assets/icons/partners/hotellijaravintolamuseo.png
  src/assets/icons/partners/hurjaruuth.png
  src/assets/icons/partners/jaes.png
  src/assets/icons/partners/kansallismuseo.png
  src/assets/icons/partners/kansallisteatteri.png
  src/assets/icons/partners/kavi.png
  src/assets/icons/partners/kulttuuriperintokasvatus.png
  src/assets/icons/partners/mfa.png
  src/assets/icons/partners/nukketeatterisampo.png
  src/assets/icons/partners/oodihelsinki.png
  src/assets/icons/partners/oopperabaletti.png
  src/assets/icons/partners/qteatteri.png
  src/assets/icons/partners/svenskateatern.png
  src/assets/icons/partners/tanssintalo.png
  src/assets/icons/partners/teatteriilmio.png
  src/assets/icons/partners/teatterimuseo.png
  src/assets/icons/partners/valokuvataiteenmuseo.png
  src/common/translation/i18n/sv.json
Labels: enhancement
